# Exercise configuration file

agent_base: "duckietown_baseline"
ws_dir: "solution" # directory that contains the code the user needs to see
log_dir: "logs" # directory that we should mount to put logs in
lab_dir: .         # directory to be mounted into the jupyter container
agent_run_cmd: "run.sh" # the script in "launchers" to run the agent with
ros: true
challenge: mooc-ros-template
rsync_exclude:
  - "solution/duckietown_dataset"
  - "solution/logs"

