# default parameters for lane_filter/histogram_lane_filter_node

debug : True
predict_frequency: 30.0 # in Hz
lane_filter_histogram_configuration:
  # ADD PARAMETERS HERE
  mean_d_0: 0
  mean_phi_0: 0
  sigma_d_0: 0.1
  sigma_phi_0: 0.1
  delta_d: 0.02
  delta_phi: 0.1
  d_max: 0.3
  d_min: -0.3
  phi_min: -1.5
  phi_max: 1.5
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  sigma_d_mask: 1.0
  sigma_phi_mask: 2.0
  range_min: 0.2
  range_est: 0.45
  range_max: 0.6
  encoder_resolution: 135
  wheel_radius: 0.0318
  wheel_baseline: 0.1
